name = "agro-group"
compatibility_date = "2024-11-01"
pages_build_output_dir = "dist"

[[kv_namespaces]]
binding = "RATE_LIMIT_KV"
id = "PLACEHOLDER_KV_ID"
preview_id = "PLACEHOLDER_KV_PREVIEW_ID"

[vars]
CONTACT_EMAIL = "contact@agro-group.com"
FROM_EMAIL = "noreply@agro-group.com"
